[package]
name = "SNN"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.2"
rand_distr = "0.5.1"
plotters = "0.3.7"
petgraph = "0.8.2"
image = "0.24.9"
indicatif = "0.18.0"
rayon = "1.10"
